<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="FastEndpoints" />
    <PackageReference Include="FastEndpoints.Swagger" />
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Serilog.Sinks.Console" />
    <PackageReference Include="Serilog.Enrichers.Environment" />
    <PackageReference Include="Serilog.Enrichers.Process" />
    <PackageReference Include="Serilog.Enrichers.Thread" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Matloob.Domain\Matloob.Domain.csproj" />
    <ProjectReference Include="..\Matloob.Contracts\Matloob.Contracts.csproj" />
  </ItemGroup>

</Project>
