using Matloob.Domain.Common;

namespace Matloob.Domain.Assets;

/// <summary>
/// A single uploaded file. The bytes live wherever <see cref="StorageDriver"/>
/// says; this row is the source of truth for everything else (original name,
/// MIME type, hash, visibility, ownership).
///
/// API responses never expose <see cref="RelativePath"/> or <see cref="StoredFileName"/>.
/// Callers download by GUID through the Assets endpoints, which stream the
/// bytes from the IFileStorage abstraction — that boundary is what lets us
/// swap Local for S3 later without churning consumers.
/// </summary>
public sealed class Asset : BaseAuditableEntity<Guid>, IAggregateRoot
{
    /// <summary>Name the uploader sent (used in Content-Disposition on download).</summary>
    public string OriginalFileName { get; private set; } = string.Empty;

    /// <summary>On-disk name generated by the storage driver. Never echoed to API consumers.</summary>
    public string StoredFileName { get; private set; } = string.Empty;

    /// <summary>RFC 6838 media type — taken from the upload, not sniffed.</summary>
    public string ContentType { get; private set; } = string.Empty;

    public long SizeBytes { get; private set; }

    /// <summary>Lower-case hex SHA-256 of the file bytes. Used for dedupe + integrity checks.</summary>
    public string Sha256 { get; private set; } = string.Empty;

    /// <summary>
    /// Driver-scoped relative path (e.g. <c>2026/05/21/0f3a...bin</c>). NEVER
    /// surfaced via API — the GUID is the only handle external callers get.
    /// </summary>
    public string RelativePath { get; private set; } = string.Empty;

    public AssetStorageDriver StorageDriver { get; private set; } = AssetStorageDriver.Local;
    public AssetVisibility Visibility { get; private set; } = AssetVisibility.Private;
    public AssetPurpose Purpose { get; private set; } = AssetPurpose.Generic;

    /// <summary>
    /// Sub claim of the uploader. Nullable so system / background uploads can
    /// own rows without a user identity. Matches the string-based UserId on
    /// <see cref="ICurrentUser"/> until the Users table lands in a later phase.
    /// </summary>
    public string? OwnerUserId { get; private set; }

    /// <summary>
    /// Establishment the upload is "for", if any. Soft FK — no DB constraint
    /// yet because the Establishment table arrives in a later phase.
    /// </summary>
    public Guid? OwnerEstablishmentId { get; private set; }

    /// <summary>
    /// Free-form caller metadata (e.g. a logical document slot, source flow,
    /// or anti-fraud signals). Stored as JSON so callers can add keys without
    /// a schema change. Optional; never required by the upload endpoint.
    /// </summary>
    public string? MetadataJson { get; private set; }

    private Asset() { }

    public Asset(
        Guid id,
        string originalFileName,
        string storedFileName,
        string contentType,
        long sizeBytes,
        string sha256,
        string relativePath,
        AssetStorageDriver storageDriver,
        AssetVisibility visibility,
        AssetPurpose purpose,
        string? ownerUserId = null,
        Guid? ownerEstablishmentId = null,
        string? metadataJson = null)
    {
        Id = id;
        OriginalFileName = originalFileName;
        StoredFileName = storedFileName;
        ContentType = contentType;
        SizeBytes = sizeBytes;
        Sha256 = sha256;
        RelativePath = relativePath;
        StorageDriver = storageDriver;
        Visibility = visibility;
        Purpose = purpose;
        OwnerUserId = ownerUserId;
        OwnerEstablishmentId = ownerEstablishmentId;
        MetadataJson = metadataJson;
    }
}
